### ISSUE TITLE
Same TIP for QA and PROD

### ISSUE THREAD

**Issue by petod108** [opendevstack/ods-document-generation-svc#50]
We use ODS v2.x
In the process to going to publish to production.
The document TIP (technical installation plan) was generated same for QA and for PROD.
Is this correct?
Our validation manager is asking for separate documents.

**Comment by clemensutschig** [comment]
this is not a bug / there is ONE TIP - and the TIR contains the env specifics. This is also described in the SOP and ok'ed by IT QA.
ping me offline if this is an issue
